import type { Metadata } from "next";

import "./globals.css";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import dotenv from "dotenv";

dotenv.config({ quiet: true });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <div className="appContainer">
          <Header></Header>
          <main>{children}</main>

          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
